### PR TITLE
Foreign credit transfer 6

### PR DESCRIPTION
**Pull request by toooni**
- implemented `ForeignCreditTransfer`
- added the currency GBP
- created a MoneyInterface because the Currency in `ForeignCreditTransfer` is not unique

I tested the output xml (~5000 lines) with ~50 payments mixed (CHF, EUR and GBP) from two outgoing accounts in the Postfinance test-platform. Everything went well. I just got 71 notifications (SEPA Payments - type 5):

image

I don't know what to do there. But It's not an error nor a warning. I think that shouldn't be a problem.

### CODE REVIEW

**Comment by z38** [comment]
Thank you very much for your contribution!

Just to clarify as I'm not sure whether I understand you correctly: Why do we need `MoneyInterface`? Wouldn't it be sufficient to just use `Money` instead?

Regarding the payment type: I think this should be fine. I will implement an option to specify the payment type in `Z38\SwissPayment\PaymentInformation\PaymentInformation` such that one could avoid this note.

**Comment by toooni** [comment]
PHPStorm complained when I was trying to use the abstract Money class as typehint for `$amount` in the `ForeignCreditTransfer` constructor. Now I am not sure anymore if this would have worked. I'll check again.

**Comment by toooni** [comment]
OK, I checked. There's no reason to use `MoneyInterface`. I'll have the PR updated in some minutes, Sorry..

**Comment by toooni** [comment]
done

**Comment by z38** [comment]
Thank you! In case the library does meet your project requirements, I would release v0.3.0 soon. What do you think?

**Comment by toooni** [comment]
All our requirements are met. So I'll look forward to it. Thanks..

**Comment by z38** [comment]
Just for future reference: If you add your SEPA transactions to `Z38\SwissPayment\PaymentInformation\SEPAPaymentInformation` the payment type is now set on B-level (as recommended).

**Comment by toooni** [comment]
Perfect! Thanks.. I honestly didn't knew what to do there ;)

**Pull request merged**
