### PR TITLE
QR Bill with QR Reference or Creditor Reference

### PR DESCRIPTION
**Pull request by sdespont**
Permits to create 2 new BankCreditTransfer specializations

- BankCreditTransferWithCreditorReference
- BankCreditTransferWithQRR

And produce correct XML structure

### CODE REVIEW

**Comment by sdespont** [comment]
@z38 ping

**Comment by eric-reichenbach** [comment]
Nice pull request, works well. Would it be possible to merge it @z38 ?

**Comment by sdespont** [comment]
@z38 Could you please consider to merge this PR? It is working on my side since june 2020.

**Comment by z38** [comment]
I'm very sorry for not responding sooner. Please see #47 about the plans for the future. If a fork emerges, I think this would be a very valuable contribution and good feature to get users move over to a new version.

**Pull request closed without merging**
