### PR TITLE
Expand IID extraction to IBANs from Liechtenstein

### LINKED ISSUE #34: IID extraction should support IBANs from Liechtenstein
`IID::fromIBAN()` currently only supports IBANs from Switzerland. The same information is also contained in IBANs from Liechtenstein.

### PR DESCRIPTION
**Pull request by sprain**
Fixes #34

### CODE REVIEW

**Comment by sprain** [comment]
Any chance this will get merged?

**Comment by z38** [comment]
Thank you! I'm sorry it took me that long to review your PR.

**Comment by sprain** [comment]
Thanks! Just the update on Packagist for v0.7.0 is missing ;) 
https://packagist.org/packages/z38/swiss-payment

**Comment by z38** [comment]
Oh, thank you for the notification! :pray: The release is now available on Packagist too.

**Pull request merged**
