### PR TITLE
gitignore

### PR DESCRIPTION
**Pull request by WebDevMichael**

### CODE REVIEW

**Comment by WebDevMichael** [comment]
gitignore

**Comment by z38** [comment]
Thank you for your contribution! Would you mind squashing your changes into 1-3 commits?

**Comment by z38** [comment]
Thanks again for your contributions. Based on your work, I refactored the code for account identifiers and added an option to specfiy an intermediary agent. Now, there is `Z38\SwissPayment\GeneralAccount` which can be used for any type of account identifier. You can find an example in the [corresponding test case](https://github.com/z38/swiss-payment/blob/0a5bebe9639619565dce732c0a5424192559bfd4/tests/Z38/SwissPayment/Tests/Message/CustomerCreditTransferTest.php#L102-111).

Feel free to add improvements or add some notes. I would be happy to receive some feedback ;)

**Comment by z38** [comment]
Hi, I'm closing this for now. Please feel free to open a new issue/PR if you encounter any issues or areas of improvement. Happy coding!

**Pull request closed without merging**
