### PR TITLE
implemented type 5 - foreign SEPA

### PR DESCRIPTION
**Pull request by toooni**
I had to implement a Mixed-Currency because the "CtrlSum" in the "GrpHdr" does not care about currencies (https://gist.github.com/toooni/200db56e932a16210e6a#file-pain_001_beispiel_1-xml-L138) - It's just a sum of all amounts.
I didn't know what to do about the mixed currencies. Maybe you have a better idea?

As soon as this PR will be merged. I will start implement type 6.

### CODE REVIEW

**Comment by z38** [comment]
Thank you very much for your contribution!

I made two small changes: renaming `ForeignSEPACreditTransfer` to `SEPACreditTransfer` and keeping the inherited equality checks for mixed currencies such that `$chf->equals($mixed) === $mixed->equals($chf)`. Please let me know in case you want to revert these changes.

Regarding mixed currencies: I think your chosen approach seems to fit for the moment. Sometime ago I thought about dropping the money stuff altogether and replace it with [Mathias Verraes' money library](https://github.com/mathiasverraes/money).

**Comment by toooni** [comment]
Thanks to you! That's perfect. How should I name the implementation for type 6? (The title of type 5 was Foreign SEPA and type 6 is just Foreign according to the Implementation Guidelines.)

I saw that money stuff in a branch, but I don't think it matters very much. The mixing of currencies would just be more complicated with the Money library.

**Comment by z38** [comment]
I think something like `ForeignCreditTransfer` or `InternationalCreditTransfer` should work fine.

**Comment by toooni** [comment]
ok, thanks..

**Pull request merged**
